apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: data-stack
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: kafka
      targetRevision: 32.4.3
      helm:
        releaseName: kafka
        valueFiles:
          - $values/argocd/apps/kafka/values/dev.yaml
    - repoURL: https://github.com/your-org/data_stack.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
