apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: data-stack
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.20.0
      helm:
        releaseName: airflow
        valueFiles:
          - $values/argocd/apps/airflow/values/dev.yaml
    - repoURL: https://github.com/your-org/data_stack.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
