apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-consumer
  namespace: data-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-consumer
  template:
    metadata:
      labels:
        app: log-consumer
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app
        image: docker.io/morheus/log-consumer:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: app-logs
