apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: kafka
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka-prod
      - op: replace
        path: /spec/sources/0/helm/valueFiles/0
        value: $values/argocd/apps/kafka/values/prod.yaml
