apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/airflow/overlays/dev
  - ../../apps/kafka/overlays/dev
  - ../../apps/log-producer/overlays/dev
  - ../../apps/log-consumer/overlays/dev
