apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: airflow
    patch: |-
      - op: replace
        path: /metadata/name
        value: airflow-dev
      - op: replace
        path: /spec/sources/0/helm/valueFiles/0
        value: $values/argocd/apps/airflow/values/dev.yaml
