defaultAirflowRepository: apache/airflow
defaultAirflowTag: "3.2.0"
executor: CeleryExecutor

webserver:
  replicas: 1

scheduler:
  replicas: 1

workers:
  replicas: 1

config:
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
