apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: log-producer
    patch: |-
      - op: replace
        path: /metadata/name
        value: log-producer-prod
      - op: replace
        path: /spec/source/path
        value: apps/log-producer/overlays/prod
