apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: data-stack
  sources:
  - repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.51.0
    helm:
      releaseName: kafka
      valueFiles:
      - $values/argocd/apps/kafka/values/dev.yaml
  - repoURL: https://github.com/your-org/data_stack.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
